version: '3'
services:
  wog:
    image: skruvi/worldofgames:latest
    restart: always
    build: .
    ports:
      - "8777:8777"
    volumes:
      - /c/Users/skruvi/PycharmProjects/WorldOfGames/Scores.txt:/Scores.txt
  